version: "3.8"  # docker-composeファイル形式v3.8
services:       # サービスの一覧
  # 【サービス名】pukiwiki
  pukiwiki:
    # 【ビルド】ローカル上にあるDockerfileを指定
    build:
      context: .
      dockerfile: Dockerfile
    # 【ポート番号】(書式: - ホスト上のポート番号:Docker上のポート番号)
    ports:                             # ポート番号
      - 9080:80                        # HTTP
    # 【ボリューム】(書式: - ホスト上のパス:Docker上のパス)
    volumes:                                              # ボリューム
      - ./wiki:/ext                                       # データ保管場所
    # 【再起動】
    restart: unless-stopped            # 手動で停止されない限りは自動起動
